name: imithon
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <4.0.0"  # Ensure this range covers Dart 3.x (change it as needed)

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.0.0
dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "imithon/rasm.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "imithon/rasm.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "imithon/rasm.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "imithon/rasm.jpg"

flutter:
  uses-material-design: true
  assets:
    - imtihon/